[workspace]
members = ["crates/derive"]

[workspace.dependencies]
convert_case = "0.7.1"
const_format = "0.2.34"
itertools = "0.14.0"

[package]
name = "cpu-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
cpu_sim_derive = { path = "crates/derive" }
const_format = { workspace = true }
elf = "0.7.4"
libc = "0.2.169"

[build-dependencies]
convert_case = { workspace = true }
itertools = { workspace = true }
